CREATE TABLE Engenheiro(
    REGISTRO_IMOVEL_OBRA INT,
    NUMERO_CREA INT,
    ID_PROJETO INT,
    NOME VARCHAR(40),
    DATA_NASCIMENTO DATE,
    CONSTRAINT PK_ENGENHEIRO PRIMARY KEY(NUMERO_CREA, REGISTRO_IMOVEL,ID_PROJETO)
);

CREATE TABLE Arquiteto(
    ID_PROJETO INT,
    ID_ARQUITETO INT,
    DATA_NASCIMENTO DATE,
    NOME VARCHAR (40),
    CONSTRAINT PK_ARQUITETO PRIMARY KEY(ID_ARQUITETO, ID_PROJETO)
);

CREATE TABLE Projeto(
    ID_EMPRESA INT,
    CNPJ_EMPRESA VARCHAR(11),
    ID_ARQUITETO INT,
    NUMERO_CREA_ENGENHEIRO INT,
    NOME VARCHAR(40),
    AREA_OCUPADA FLOAT,
    ID_PROJETO INT,
    CONSTRAINT PK_PROJETO PRIMARY KEY(ID_ARQUITETO, NUMERO_CREA_ENGENHEIRO, ID_ARQUITETO, ID_EMPRESA, CPF_EMPRESA)
);

CREATE TABLE Obra(
    CUSTO FLOAT,
    PRAZO DATE,
    ID_LOCAL INT,
    NUMERO_CREA_ENGENHEIRO INT,
    ID_GERENTE INT,
    CPF_GERENTE VARCHAR(11),
    REGISTRO_IMOVEL INT,
    DATA_INICIO DATE,
    DATA_TERMINO DATE,
    CONSTRAINT PK_OBRA PRIMARY KEY(REGISTRO_IMOVEL, CPF_GERENTE, ID_GERENTE, NUMERO_CREA_ENGENHEIRO, ID_LOCAL)
);

CREATE TABLE Local_(
    /*adicionar os atributos compostos de endereço conforme o modelo lógico*/
    ID_EMPRESA INT,
    CNPJ_EMPRESA VARCHAR(11),
    REGISTRO_IMOVEL_OBRA INT,
    ID_LOCAL INT,
    ZONEAMENTO FLOAT
    CONSTRAINT PK_LOCAL PRIMARY KEY(ID_LOCAL, REGISTRO_IMOVEL_OBRA, ID_EMPRESA, CPF_EMPRESA)
);

CREATE TABLE Empresa_Contratante(
    ID_PROJETO INT,
    ID_LOCAL INT,
    ID_EMPRESA INT,
    CPF VARCHAR(11),
    CONSTRAINT PK_EMPRESA_CONTRATANTE PRIMARY KEY(ID_EMPRESA, CPF, ID_LOCAL, ID_PROJETO)
);

CREATE TABLE Pedreiro(
    NOME VARCHAR(40),
    DATA_NASCIMENTO DATE,
    ID_EMPREITEIRA INT,
    CNPJ_EMPREITEIRA VARCHAR(11),
    CPF VARCHAR(11),
    ID_PEDREIRO INT,
    CONSTRAINT PK_PEDREIRO PRIMARY KEY(CPF, ID_PEDREIRO, CNPJ_EMPREITEIRA, ID_EMPREITEIRA)
);

CREATE TABLE Pedreiro_trabalha_em_obra(
    CPF_PEDREIRO VARCHAR(11),
    ID_PEDREIRO INT,
    REGISTRO_IMOVEL INT,
    CONSTRAINT PK_PEDREIRO_TRABALHA_EM_OBRA PRIMARY KEY(CPF_PEDREIRO, ID_PEDREIRO, REGISTRO_IMOVEL)
);

CREATE TABLE Gerente_de_Obras(
    ID_GERENTE INT,
    CPF VARCHAR(11),
    ID_EMPREITEIRA INT,
    CNPJ_EMPREITEIRA VARCHAR(11),
    REGISTRO_IMOVEL_OBRA INT,
    NOME VARCHAR(40),
    DATA_NASCIMENTO DATE,
    DATA_ADMISSAO DATE,
    CONSTRAINT PK_GERENTE_DE_OBRAS PRIMARY KEY(ID_GERENTE, CPF, ID_EMPREITEIRA, CNPJ_EMPREITEIRA, REGISTRO_IMOVEL_OBRA)
);

CREATE TABLE Empreiteira(
    CPF_PEDREIRO VARCHAR(11),
    ID_PEDREIRO INT,
    ID_EMPREITEIRA INT,
    CNPJ VARCHAR(11),
    ID_GERENTE INT,
    CPF_GERENTE VARCHAR(11),
    /*inserir os atributos compostos segundo o modelo lógico*/
    CONSTRAINT PK_EMPREITEIRA PRIMARY KEY(ID_EMPREITEIRA, CNPJ, ID_GERENTE, CPF_GERENTE, CPF_PEDREIRO, ID_PEDREIRO)
);

ALTER TABLE Engenheiro
ADD CONSTRAINT FK_ENGENHEIRO_OBRA FOREIGN KEY(REGISTRO_IMOVEL_OBRA) 
REFERENCES Obra(REGISTRO_IMOVEL);

ALTER TABLE Engenheiro
ADD CONSTRAINT FK_ENGENHEIRO_PROJETO FOREIGN KEY(ID_PROJETO) 
REFERENCES Projeto(ID_PROJETO);

ALTER TABLE Arquiteto
ADD CONSTRAINT FK_ARQUITETO_PROJETO FOREIGN KEY(ID_PROJETO) 
REFERENCES Projeto(ID_PROJETO);

ALTER TABLE Projeto
ADD CONSTRAINT FK_PROJETO_ARQUITETO FOREIGN KEY(ID_ARQUITETO)
REFERENCES Arquiteto(ID_ARQUITETO);

ALTER TABLE Projeto
ADD CONSTRAINT FK_PROJETO_ENGENHEIRO FOREIGN KEY(NUMERO_CREA_ENGENHEIRO)
REFERENCES Engenheiro(NUMERO_CREA);

ALTER TABLE Projeto 
ADD CONSTRAINT FK_PROJETO_OBRA FOREIGN KEY(REGISTRO_IMOVEL_OBRA)
REFERENCES Obra(REGISTRO_IMOVEL)

ALTER TABLE Projeto 
ADD CONSTRAINT FK_PROJETO_EMPRESA_CONTRATANTE FOREIGN KEY(ID_EMPRESA, CNPJ_EMPRESA)
REFERENCES Empresa_Contratante(ID_EMPRESA, CNPJ)

ALTER TABLE Obra
ADD CONSTRAINT FK_OBRA_ENGENHEIRO FOREIGN KEY(NUMERO_CREA_ENGENHEIRO) 
REFERENCES Engenheiro(NUMERO_CREA);

ALTER TABLE Obra
ADD CONSTRAINT FK_OBRA_LOCAL FOREIGN KEY(ID_LOCAL)
REFERENCES Local_(ID_LOCAL);

ALTER TABLE Obra
ADD CONSTRAINT FK_OBRA_GERENTE_DE_OBRAS FOREIGN KEY(ID_GERENTE, CPF_GERENTE)
REFERENCES Gerente_de_Obras(CPF, ID_GERENTE);

ALTER TABLE Pedreiro_trabalha_em_obra
ADD CONSTRAINT FK_PEDREIRO_TRABALHA_EM_OBRA FOREIGN KEY(CPF_PEDREIRO, ID_PEDREIRO)
REFERENCES Pedreiro(CPF, ID_PEDREIRO);

ALTER TABLE Gerente_de_Obras
ADD CONSTRAINT FK_GERENTE_DE_OBRAS_OBRA FOREIGN KEY(REGISTRO_IMOVEL_OBRA)
REFERENCES Obra(ID_GERENTE, CPF_GERENTE);

ALTER TABLE Gerente_de_Obras
ADD CONSTRAINT FK_GERENTE_DE_OBRAS_EMPREITEIRA FOREIGN KEY(ID_EMPREITEIRA, CNPJ_EMPREITEIRA)
REFERENCES Empreiteira(CNPJ, ID_EMPREITEIRA);

ALTER TABLE Pedreiro
ADD CONSTRAINT FK_PEDREIRO_EMPREITEIRA FOREIGN KEY(ID_EMPREITEIRA, CNPJ_EMPREITEIRA)
REFERENCES Empreiteira(CPF_PEDREIRO, ID_PEDREIRO);

ALTER TABLE Local_
ADD CONSTRAINT FK_LOCAL_OBRA FOREIGN KEY(REGISTRO_IMOVEL_OBRA)
REFERENCES Obra(REGISTRO_IMOVEL);

ALTER TABLE Local_
ADD CONSTRAINT FK_LOCAL_EMPRESA_CONTRATANTE FOREIGN KEY(ID_EMPRESA, CNPJ_EMPRESA)
REFERENCES Empresa_Contratante(ID_EMPRESA, CNPJ);

ALTER TABLE Empresa_Contratante
ADD CONSTRAINT FK_LOCAL_EMPRESA_CONTRATANTE_PROJETO FOREIGN KEY(ID_PROJETO)
REFERENCES Projeto(ID_PROJETO);