CREATE TABLE Engenheiro(
    REGISTRO_IMOVEL_OBRA INT NOT NULL,
    NUMERO_CREA INT NOT NULL,
    NOME VARCHAR(40) NOT NULL,
    DATA_NASCIMENTO DATE,
    CONSTRAINT PK_ENGENHEIRO PRIMARY KEY(NUMERO_CREA, REGISTRO_IMOVEL_OBRA)
);

CREATE TABLE Arquiteto(
    ID_ARQUITETO INT NOT NULL,
    DATA_NASCIMENTO DATE ,
    NOME VARCHAR (40) NOT NULL,
    CONSTRAINT PK_ARQUITETO PRIMARY KEY(ID_ARQUITETO)
);

CREATE TABLE Projeto(
    REGISTRO_IMOVEL_OBRA INT NOT NULL,
    ID_ARQUITETO INT NOT NULL,
    NUMERO_CREA_ENGENHEIRO INT NOT NULL,
    NOME VARCHAR(40) NOT NULL,
    AREA_OCUPADA FLOAT NOT NULL,
    ID_PROJETO INT NOT NULL,
    CONSTRAINT PK_PROJETO PRIMARY KEY(ID_ARQUITETO, NUMERO_CREA_ENGENHEIRO, REGISTRO_IMOVEL_OBRA)
);

CREATE TABLE Obra(
    CUSTO FLOAT NOT NULL,
    PRAZO DATE NOT NULL,
    ID_LOCAL INT,
    NUMERO_CREA_ENGENHEIRO INT NOT NULL,
    REGISTRO_IMOVEL INT NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_TERMINO DATE,
    CONSTRAINT PK_OBRA PRIMARY KEY(REGISTRO_IMOVEL, NUMERO_CREA_ENGENHEIRO, ID_LOCAL)
);

CREATE TABLE Local_(
    CIDADE VARCHAR(40) NOT NULL,
    ESTADO VARCHAR(40) NOT NULL,
    CEP VARCHAR2(40) NOT NULL,
    ID_EMPRESA INT NOT NULL,
    CNPJ_EMPRESA VARCHAR(11) NOT NULL,
    REGISTRO_IMOVEL_OBRA INT NOT NULL,
    ID_LOCAL INT NOT NULL,
    ZONEAMENTO FLOAT NOT NULL,
    CONSTRAINT PK_LOCAL PRIMARY KEY(ID_LOCAL, REGISTRO_IMOVEL_OBRA, ID_EMPRESA, CNPJ_EMPRESA)
);

CREATE TABLE Empresa_Contratante(
    CEP VARCHAR2(40) NOT NULL,
    CIDADE VARCHAR2(40) NOT NULL,
    ESTADO VARCHAR2 (40) NOT NULL,
    ID_PROJETO INT NOT NULL,
    ID_LOCAL INT NOT NULL,
    ID_EMPRESA INT NOT NULL,
    CNPJ VARCHAR(11) NOT NULL,
    CONSTRAINT PK_EMPRESA_CONTRATANTE PRIMARY KEY(ID_EMPRESA, CNPJ, ID_LOCAL, ID_PROJETO)
);

CREATE TABLE Pedreiro(
    NOME VARCHAR(40) NOT NULL,
    DATA_NASCIMENTO DATE,
    CPF VARCHAR(11) NOT NULL,
    ID_PEDREIRO INT NOT NULL,
    CONSTRAINT PK_PEDREIRO PRIMARY KEY(CPF, ID_PEDREIRO)
);

CREATE TABLE Pedreiro_trabalha_em_obra(
    CPF_PEDREIRO VARCHAR(11) NOT NULL,
    ID_PEDREIRO INT NOT NULL,
    REGISTRO_IMOVEL INT NOT NULL,
    CONSTRAINT PK_PEDREIRO_TRABALHA_EM_OBRA PRIMARY KEY(CPF_PEDREIRO, ID_PEDREIRO, REGISTRO_IMOVEL)
);

CREATE TABLE Gerente_de_Obras(
    ID_GERENTE INT NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    ID_EMPREITEIRA INT NOT NULL,
    CNPJ_EMPREITEIRA VARCHAR(11) NOT NULL,
    REGISTRO_IMOVEL_OBRA INT NOT NULL,
    NOME VARCHAR(40) NOT NULL,
    DATA_NASCIMENTO DATE,
    DATA_ADMISSAO DATE,
    CONSTRAINT PK_GERENTE_DE_OBRAS PRIMARY KEY(ID_GERENTE, CPF, ID_EMPREITEIRA, CNPJ_EMPREITEIRA, REGISTRO_IMOVEL_OBRA)
);

CREATE TABLE Empreiteira(
    CPF_PEDREIRO VARCHAR(11) NOT NULL,
    ID_PEDREIRO INT NOT NULL,
    ID_EMPREITEIRA INT NOT NULL,
    CNPJ VARCHAR(11) NOT NULL,
    ID_GERENTE INT NOT NULL,
    CPF_GERENTE VARCHAR(11) NOT NULL,
    CEP VARCHAR2(40) NOT NULL,
    CIDADE VARCHAR2(40) NOT NULL,
    ESTADO VARCHAR2 (40) NOT NULL,
    CONSTRAINT PK_EMPREITEIRA PRIMARY KEY(ID_EMPREITEIRA, CNPJ, ID_GERENTE, CPF_GERENTE, CPF_PEDREIRO, ID_PEDREIRO)
);

ALTER TABLE Projeto
ADD CONSTRAINT FK_PROJETO_ARQUITETO FOREIGN KEY(ID_ARQUITETO)
REFERENCES Arquiteto(ID_ARQUITETO);

ALTER TABLE Projeto
ADD CONSTRAINT FK_PROJETO_ENGENHEIRO FOREIGN KEY(NUMERO_CREA_ENGENHEIRO)
REFERENCES Engenheiro(NUMERO_CREA);

ALTER TABLE Projeto 
ADD CONSTRAINT FK_PROJETO_OBRA FOREIGN KEY(REGISTRO_IMOVEL_OBRA)
REFERENCES Obra(REGISTRO_IMOVEL);

ALTER TABLE Obra
ADD CONSTRAINT FK_OBRA_ENGENHEIRO FOREIGN KEY(NUMERO_CREA_ENGENHEIRO) 
REFERENCES Engenheiro(NUMERO_CREA);

ALTER TABLE Obra
ADD CONSTRAINT FK_OBRA_LOCAL FOREIGN KEY(ID_LOCAL)
REFERENCES Local_(ID_LOCAL);

ALTER TABLE Obra
ADD CONSTRAINT FK_OBRA_GERENTE_DE_OBRAS FOREIGN KEY(ID_GERENTE, CPF_GERENTE)
REFERENCES Gerente_de_Obras(CPF, ID_GERENTE);

ALTER TABLE Pedreiro_trabalha_em_obra
ADD CONSTRAINT FK_PEDREIRO_TRABALHA_EM_OBRA FOREIGN KEY(CPF_PEDREIRO, ID_PEDREIRO)
REFERENCES Pedreiro(CPF, ID_PEDREIRO);

ALTER TABLE Gerente_de_Obras
ADD CONSTRAINT FK_GERENTE_DE_OBRAS_EMPREITEIRA FOREIGN KEY(ID_EMPREITEIRA, CNPJ_EMPREITEIRA)
REFERENCES Empreiteira(CNPJ, ID_EMPREITEIRA);

ALTER TABLE Pedreiro
ADD CONSTRAINT FK_PEDREIRO_EMPREITEIRA FOREIGN KEY(ID_EMPREITEIRA, CNPJ_EMPREITEIRA)
REFERENCES Empreiteira(CPF_PEDREIRO, ID_PEDREIRO);

ALTER TABLE Local_
ADD CONSTRAINT FK_LOCAL_EMPRESA_CONTRATANTE FOREIGN KEY(ID_EMPRESA, CNPJ_EMPRESA)
REFERENCES Empresa_Contratante(ID_EMPRESA, CNPJ);

ALTER TABLE Empresa_Contratante
ADD CONSTRAINT FK_LOCAL_EMPRESA_CONTRATANTE_PROJETO FOREIGN KEY(ID_PROJETO)
REFERENCES Projeto(ID_PROJETO);
